services:
  web:
    build: ./clipper_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./clipper_backend/:/usr/src/clipper_backend/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=clipper

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # Regular celery worker processes videos
  celery:
    build: ./clipper_backend
    command: celery -A clipper_backend worker -l info
    volumes:
      - ./clipper_backend/:/usr/src/clipper_backend/
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./clipper_backend/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./clipper_backend/media/:/media/
volumes:
  postgres_data:
  media_files:
