# Generated by Django 5.2.3 on 2025-06-29 13:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClipFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clip_file', models.FileField(blank=True, null=True, upload_to='clips/')),
                ('clip_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('file_size', models.BigIntegerField()),
                ('duration', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('videofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='videos.videofile')),
            ],
        ),
    ]
