# Generated by Django 5.2.3 on 2025-06-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_clipfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='clipfile',
            name='in_point',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clipfile',
            name='out_point',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
