# Generated by Django 5.2.3 on 2025-06-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_clipfile_in_point_clipfile_out_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='clipfile',
            name='original_video_id',
            field=models.CharField(blank=True),
        ),
    ]
