# Generated by Django 5.2.3 on 2025-06-29 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_clipfile_original_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clipfile',
            name='original_video_id',
        ),
    ]
