# Generated by Django 5.2.3 on 2025-06-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_remove_clipfile_original_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clipfile',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
