# Generated by Django 5.2.3 on 2025-06-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_alter_clipfile_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='clipfile',
            name='clip_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
