# Generated by Django 5.2.3 on 2025-06-30 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_clipfile_clip_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clipfile',
            name='clip_filename',
        ),
    ]
