# Generated by Django 5.2.3 on 2025-07-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_remove_clipfile_clip_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='framerate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
